name: Linux SSH Server

on: [workflow_dispatch]  # Run manually

jobs:
  linux-ssh:
    runs-on: ubuntu-latest  # Linux VM
    steps:
      - name: Install OpenSSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo mkdir -p /run/sshd  # Required for SSH in containerized env

      - name: Set SSH Password (or use keys)
        run: |
          echo "runneradmin:P@ssw0rd!" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Download Ngrok (Linux)
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
          tar xzf ngrok.tgz

      - name: Authenticate Ngrok
        run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start SSH and expose with Ngrok
        run: |
          sudo service ssh start
          ./ngrok tcp 22 --log=stdout > ngrok.log &
          sleep 5  # Wait for Ngrok to start
          grep "url=tcp://" ngrok.log | sed 's/.*url=tcp://g' | awk '{print "SSH Host: " $1}'  # Extract Ngrok host
